ID = 'id'
ENABLED = 'enabled'
TRIGGER = 'trigger'
ACTIONS = 'actions'

TYPE = 'type'
DAYS = 'days'
TIME = 'time'
TOPIC = 'topic'
VALUE = 'value'
FILE = 'file'
DELAY = 'delay'
RETAINED = 'retained'
CONDITION = 'condition'

BROKER_TYPE = 'broker'
SCENARIO_TYPE = 'scenario'
